### ISSUE TITLE
video is not defined

### ISSUE THREAD

**Issue by Nodalailama** [muxinc/hls-video-element#10]
Hi,

https://github.com/muxinc/hls-video-element/blob/57c4a5e32ba87536604e2b751bb60a5db87b0e78/index.js#L35

_video.canPlayType_ should be replaced by _this.nativeEl.canPlayType_

Cordialement,

**Comment by jools-r** [comment]
Observing this too in Mobile Safari iOS 15.4.1 but not on desktop Safari when using:

`<script type="module" src="https://unpkg.com/hls-video-element@0.0"></script>`

in conjunction with [Media Chrome](https://github.com/muxinc/media-chrome). The poster image loads but the video itself doesn't.

You can observe this on the [Media Chrome HLS Media Demo](https://media-chrome.mux.dev/examples/media-elements/hls.html) too.

```
ReferenceError: Can't find variable: video

ReferenceError: Can't find variable: video
load hls – video-element.js:84:1170
connectedCallback – hls-video-element.js:84:1275
define
Modulcode – hls-video-element.js:84:1348
evaluate
moduleEvaluation
(anonyme Funktion)
promiseReactionJob
```

If I'm reading it correctly, [Nodalailama](https://github.com/Nodalailama) provided a [PR](https://github.com/muxinc/hls-video-element/pull/13) but as it's not incorporated, it's not part of the version on unpkg.com.
