### ISSUE TITLE
loadSource and attachMedia should respect a good event order

### ISSUE THREAD

**Issue by Nodalailama** [muxinc/hls-video-element#11]
Hi,

As reading hls doc https://github.com/video-dev/hls.js/blob/master/docs/API.md#third-step-load-a-manifest, 
it is recommended to 1) _attachMedia_ then 2) listen to _MEDIA_ATTACHED_ event and then 3) when this event is fired, we can _loadSource_.

https://github.com/muxinc/hls-video-element/blob/57c4a5e32ba87536604e2b751bb60a5db87b0e78/index.js#L33

```
hls.attachMedia(this.nativeEl);
hls.on(Hls.Events.MEDIA_ATTACHED, () => hls.loadSource(this.src));
```

Cordialement,

**Comment by luwes** [comment]
this seems to be inline now with the docs. thanks for the feedback!
