### ISSUE TITLE
Support tracks (subtitles, thumbnails) as children of the element

### ISSUE THREAD

**Issue by AdrianMrn** [muxinc/hls-video-element#6]
Hey! We're using this library and media-chrome, I'd like to add a thumbnail track in combination with support for m3u8 files that I pull from Mux, so basically this:

https://github.com/muxinc/media-chrome/blob/4c4ef8a03aaef406d6ebfd14f8f737d7a523552b/examples/control-elements/media-clip-selector.html#L18-L24

but with the hls-video element. I've tried extending/copying the hls-video web component, but I haven't figured out how to place the track into the actual <video> tag.

I was hoping this would work:
```
<hls-video-custom slot="media" src={videoSrc}>
  <track
    slot="media"
    label="thumbnails"
    default
    kind="metadata"
    src={`https://image.mux.com/${playbackId}/storyboard.vtt`}
  ></track>
</hls-video-custom>
```

It looks like maybe `custom-video-element` should allow appending children to the native `video` element here: https://github.com/muxinc/custom-video-element/blob/8723e13a7622c23bb277b518afd300ddae3dbde2/index.js#L43

Maybe something like this in custom-video-element?

```js
if (template.nativeChild) {
  nativeEl.appendChild(template.nativeChild);
}
```

**Comment by heff** [comment]
Glad you were able to figure it out!

I think we should be supporting it as a child track if possible in custom-video-element. Not sure how that's going to work with custom element slots, but it's worth figuring out.

Going to re-open and rename this.

**Comment by AdrianMrn** [comment]
Sound good 👍  let me know if you need me to try anything out.

**Comment by heff** [comment]
@AdrianMrn child track elements should be working now. Give it a shot if you can.

**Comment by AdrianMrn** [comment]
@heff Thanks! This works great in combination with mux-chrome 👍
